# Generated by Django 2.2.26 on 2022-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220613_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
